language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
  - "nightly"  # nightly build
# command to install dependencies
env:
  - NEWMAIL_NOTIFY=False
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - export LOGIN_ID=test
  - export LOGIN_PW=test
  - python -m pytest
