import random
from typing import Optional

from pydantic import BaseModel
import pykakasi
kks = pykakasi.kakasi()

class Wisdom(BaseModel):
    kanji: str
    hira: Optional[str]
    eng: str

def get_wisdom_text() -> str:
    w: Wisdom = get_wisdom()
    return f'{w.eng}\n{w.kanji}\n{w.hira}\n'

def get_wisdom() -> Wisdom:
    words = list_from_words(random.randint(0, len(WISDOM_LIST) - 1))
    # convert kanji to hiragana
    converted_list = kks.convert(words.kanji)
    words.hira = " ".join([word['hira'] for word in converted_list])
    return words

def list_from_words(num: int) -> Wisdom:
    wisdom_list = WISDOM_LIST[num]
    return Wisdom(eng=wisdom_list[0], kanji=wisdom_list[1])

# Thanks for https://eigo-duke.com/quote/kakugenall.html
WISDOM_LIST = [
   ["Every man is the architect of his own fortune.", "全ての人は自分の運命を自分で決められる"],
   ["The first step is always the hardest.", "一番難しいのは最初の一歩である。"],
   ["Life is what you make it.", "人生は自分でつくるもの"],
   ["Good seed makes a good crop.", "よい穀物はよい種から生まれる。"],
   ["Faith will move mountains.", "信念は山を動かす"],
   ["Cheats never prosper.", "不正が繁栄することはない"],
   ["Better late than never.", "やらないよりは遅れてでもやるべき"],
   ["There is no royal road to learning.", "学問に王道なし"],
   ["Adversity makes a man wise.", "逆境が人を強くする"],
   ["It’s never too late to learn.", "学問に遅すぎるはない"],
   ["Failure teaches success.", "失敗は成功の母である"],
   ["Easy come, easy go.", "得やすいものは失うのも早い"],
   ["Practice makes perfect.", "練習が完璧を生む"],
   ["No pain no gain.", "痛みなく得ることはできない"],
   ["Nothing ventured, nothing gained.", "やってみなければ何も得られない"],
   ["Never put off till tomorrow what can be done today.", "やるなら今でしょ"],
   ["No sweet without sweat.", "働かずして飯は得られない"],
   ["Second thoughts are best.", "もう一度考えてみよう"],
   ["Pride will have a fall.", "自らを守るものは失敗する"],
   ["First come, first served.", "先手必勝（先にやれば得られる）"],
   ["Seeing is believing.", "百聞は一見に如かず"],
   ["No news is good news.", "知らせがないことは良いことである"],
   ["The older, the wiser.", "年を取れば賢くなる"],
   ["What will be, will be.", "なるようになる"],
   ["When in Rome do as the Romans do.", "郷に入っては郷に従え"],
   ["A good beginning makes a good ending.", "始め良ければ終わり良し"],
   ["Too far east is west.", "やり過ぎをとがめない（行き過ぎた東は西となる）"],
   ["Nothing comes of nothing.", "ゼロからは何も生じない"],
   ["The more one has, the more one wants.", "得られればさらにほしくなる"],
   ["A friend to everybody is a friend to nobody.", "みんなに良くしようとすると誰も残らない"],
   ["Who knows most, speaks least.", "沈黙は金なり(一番知っている人は一番話さない）"],
   ["Soon learnt, soon forgotten.", "覚えるのが早いことは忘れるのも早い"],
   ["What’s done is done.", "終わったことは仕方ない"],
   ["So many men, so many minds", "十人十色 (人はそれぞれ自分の考えを持っている)"],
   ["Think today and speak tomorrow.", "今は考えて次の機会に話そう"],
   ["No answer is also an answer.", "黙秘も一つの答えである"],
   ["Nothing seek, nothing find.", "探さなければ見つからない"],
   ["That’s life.", "それが人生"],
   ["Knowledge is power.", "知は力"],
   ["Travel broadens mind.", "旅により知識が広がる"],
   ["Never judge by appearances.", "人は見かけで判断できない"],
   ["Many a little makes a mickle.", "チリも積もれば山となる"],
   ["No time like the present.", "今はもう戻ってこない"],
   ["Prevention is better than cure.", "予防にまさる治療はない"],
   ["The pot calls the kettle black.", "五十歩百歩"],
   ["Time lost cannot be recalled.", "失った時間は戻ってこない"],
   ["You never miss the water till the well runs dry.", "失ってから大切なものに気付く"],
   ["Words have wings, and cannot be called.", "言葉は飛んでいく、そして取り戻すことは出来ない"],
   ["The rotten apple injures its neighbor.", "周りの悪い影響を受ける"],
   ["A friend in need is a friend indeed.", "苦しいときに助けてくれる友人が本当の友人"],
   ["While there is life there is hope.", "生きているだけで希望がある"],
   ["Two heads are better than one.", "二人の知恵の方が一人よりも良い"],
   ["Learn to walk before you run.", "石橋をたたいて渡る"],
   ["Don’t teach fishes to swim.", "魚に泳ぎ方を教える必要はない"],
   ["Money talks.", "金がものをいう"],
   ["Bad news travels fast.", "悪事千里を走る (悪い知らせはすぐ伝わる)"],
   ["A bird in the hand is worth two in the bush.", "明日の百より今日の五十 (手中の一羽は森の中の2羽にまさる)"],
   ["Fortune is fickle and blind.", "当たるも八卦当たらぬも八卦 (運は気まぐれ、分からぬもの)"],
   ["Patience wears out stones.", "石の上にも三年 (忍耐は石をも穿つ)"],
   ["Make haste slowly.", "急がば回れ (ゆっくり急げ)"],
   ["Sink or swim.", "一か八か (溺れたくなければ泳げ)"],
   ["One instance shows all.", "一事が万事 (一つの事柄ですべてが見える)"],
   ["History repeats itself.", "二度あることは三度ある (歴史は繰り返す)"],
   ["Out of the frying pan into the fire.", "一難去ってまた一難 (フライパンは脱出したが、火の中へ)"],
   ["In sickness, care first and medicine second.", "一に看病二に薬 (病には、養生一番、二に薬)"],
   ["The lucky man has a daughter for his firstborn.", "一姫二太郎 (第一子に娘をさずかるのが幸運)"],
   ["Everything has its pros and cons.", "一利あれば一害あり (何事にも良い面と悪い面がある)"],
   ["To be in the same boat.", "一蓮托生 (同じ舟に乗る)"],
   ["A word is enough to the wise.", "一を聞いて十を知る (賢者には一言で足りる)"],
   ["To fell two dogs with one stone.", "一挙両得 (一つの石で二匹の犬を倒す)"],
   ["No one knows what the future holds.", "一寸先は闇 (先のことなどわからない)"],
   ["Tread on a worm and it will turn.", "一寸の虫にも五分の魂 (虫でさえ踏みつけると向かってくる)"],
   ["To kill two birds with one stone.", "一石二鳥 (一つの石で二羽の鳥を殺す)"],
   ["A fair comlexion covers a multitude of sins.", "色の白いは七難隠す (色白は多くの罪を隠す)"],
   ["An outsider can see some things much better.", "岡目八目 (外部から見るほうがよく見えることがある)"],
   ["Everything has its time.", "鬼も十八番茶も出花 (何事にも適齢期があるものだ)"],
   ["Three women make a market.", "女三人寄れば姦しい (女三人寄れば市（いち）が立つ)"],
   ["The deepest love turns into the deepest hatred.", "可愛さ余って憎さ百倍 (最高の愛も最大の憎悪に変わりうる)"],
   ["Both eloquent and skilled.", "口八丁手八丁 (能弁・器用の兼備)"],
   ["Wine is the panacea of all ills.", "酒は百薬の長 (ワインは万病の万能薬だ)"],
   ["Safety first.", "安全第一"],
   ["The third time lucky.", "三度目の正直"],
   ["Even the longest journey begins with a single step.", "千里の道も一歩から (長い旅も一歩から始まる)"],
   ["Every man has his faults.", "なくて七癖 (誰にも欠点はあるもの)"],
   ["A rolling stone gathers no moss.", "転石苔むさず"],
   ["A man's walking is a succession of falls.", "七転び八起き (人生は転びの連続だ)"],
   ["It's like fanning the sun with a peacock's feather.", "二階から目薬 (クジャクの羽で太陽をあおぐようなものだ)"],
   ["To wear two hats.", "二足の草鞋を履く (二個の帽子をかぶる)"],
   ["Even thieves have their reasons.", "盗人にも三分の理 (盗人にも言い訳があるものだ)"],
   ["Everybody's friend.", "八方美人 (みんなの友達)"],
   ["The early bird catches the worm.", "早起きは三文の得 (早起きの鳥は虫にあずかる)"],
   ["Beggars can't be choosers.", "背に腹は代えられぬ (乞食は選り好みできない)"],
   ["Hunger is the best sauce.", "空腹にまずいものなし (空腹は最高のソースだ)"],
   ["Feed by measure and defy the physician.", "腹八分目に医者いらず (適量の食事で医者を退けよ)"],
   ["A wonder lasts but nine days.", "人の噂も七十五日 (驚きも9日で終わり)"],
   ["A man dies, his name remains.", "人は一代、名は末代 (人は死ぬが、名は残る)"],
   ["Ignorance is bliss.", "知らぬが仏 (知らぬが至福)"],
   ["It is like preaching to the wind.", "馬の耳に念仏 (風に説教)"],
   ["To try the patience of a saint.", "仏の顔も三度まで (聖人の我慢をためす)"],
   ["An old dog cannot alter his way of barking.", "三つ子の魂百まで (老犬も鳴き声は変わらず)"],
   ["To fall between two stools.", "虻蜂取らず (二脚の腰掛の間にしりもち)"],
   ["The devil always leaves a stink behind him.", "鼬（いたち）の最後っ屁 (悪魔はいつも悪臭を残して去る)"],
   ["One should not interfere in lover's quarrels.", "夫婦喧嘩は犬も食わぬ (恋人同士のけんかに口をはさむべきでない)"],
   ["Every dog has his day.", "犬も歩けば棒に当たる (どの犬にも日の目を見る時がある)"],
   ["He who stays in the valley shall never get over the hill.", "井の中の蛙大海を知らず (谷底に居座るものは丘を越えられない)"],
   ["The more noble, the more humble.", "実るほど頭を垂れる稲穂かな (高貴であればあるほど謙虚だ)"],
   ["Too many cooks spoil the broth.", "船頭多くして船山に登る (料理人が多すぎるとスープがうまくできない)"],
   ["Anything viewed through the eyes of faith seems perfect.", "鰯の頭も信心から (信仰の目から見れば何事も完全)"],
   ["Throw a sprat to catch a whale.", "海老で鯛を釣る (鰯を投げてクジラを捕える)"],
   ["Fellow sufferers pity each other.", "同病相憐れむ (同じ悩みの人たちは相憐れむ)"],
   ["To be betrayed by a trusted follower.", "飼い犬に手を?まれる (信頼していた配下に裏切られる)"],
   ["Like father, like son.", "蛙の子は蛙 (この父にしてこの子あり)"],
   ["Years bring wisdom.", "亀の甲より年の功 (年を重ねると知恵がつく)"],
   ["Despair gives courage to a coward.", "窮鼠（きゅうそ）猫を?む (臆病者でも絶望の果てには勇気が出る)"],
   ["Unused treasure is a waste of treasure.", "宝の持ち腐れ (宝も使わねば無駄物)"],
   ["It's like beating the air.", "豆腐にかすがい (空気を殴るようなものだ)"],
   ["A good horse becomes never a jade.", "腐っても鯛 (駿馬は駄馬にはならない)"],
   ["To fudge the count.", "鯖を読む (数をごまかす)"],
   ["Even Homer sometimes nods.", "弘法も筆の誤り (ホーマーでさえ時には居眠りする)"],
   ["Those who hide can find.", "蛇（じゃ）の道は蛇（へび） (隠し慣れた人は見つけるのも早い)"],
   ["There is no accounting for tastes.", "蓼（たで）食う虫も好き好き (人の好みはそれぞれで説明できない)"],
   ["Don't count your chickens before they are hatched.", "捕らぬ狸の皮算用 (卵がかえる前にひなを数えるな)"],
   ["Misfortunes never come singly.", "泣きっ面に蜂 (不幸は続くものだ)"],
   ["Fortune is unpredictable and changeable.", "人間万事塞翁が馬 (運は予測できず、変幻自在だ)"],
   ["Still waters run deep.", "能ある鷹は爪を隠す (静かに流れる川は深い)"],
   ["Honey is sweet, but the bee stings.", "河豚（ふぐ）は食いたし命は惜しし (蜂蜜は甘いが、蜂は刺す)"],
   ["A disciple sometimes outshines his master.", "青は藍より出でて藍より青し (弟子が師を超えることもある)"],
   ["The shoemaker's son always goes barefoot.", "紺屋の白袴 (靴屋の息子はいつもはだしで歩く)"],
   ["He who touches pitch shall be defiled.", "朱に交われば赤くなる (瀝青に触れれば汚れる)"],
   ["The grass is greener on the other side of the fence.", "隣の花は赤い (隣の芝生は青い)"],
   ["We never meet without parting.", "会うは別れの始め (会えば必ず別れがくる)"],
   ["Ill-gotten, ill-spent.", "悪銭身に付かず (不当に得たものは不当に使われる)"],
   ["It's no use crying over spilt milk.", "覆水盆に返らず (一度こぼれたミルクは取り戻せない)"],
   ["I don't care what follows.", "後は野となれ山となれ (後で何が起ころうと知ったことじゃない)"],
   ["Love is blind.", "あばたもえくぼ (愛は盲目)"],
   ["After a storm comes a calm.", "雨降って地固まる (嵐の後には凪（なぎ）がくる)"],
   ["Physician, heal thyself.", "医者の不養生 (医者よ、汝自身を治せ)"],
   ["Food before romance", "色気より食い気"],
   ["Easier said than done.", "言うは易く行うは難し"],
   ["Better leave it unsaid.", "言わぬが花"],
   ["As a man sows, so shall he reap.", "因果応報 (蒔いた種は刈らねばならぬ)"],
   ["There is no limit to excellence.", "上には上がある (卓越さに上限なし)"],
   ["It is breading and not birth that makes a man.", "氏より育ち"],
   ["Many a true word is spoken in jest.", "嘘から出た実（まこと） (ふざけ言葉がまことになったものは多い)"],
   ["He that will lie, will steal.", "?つきは泥棒の始まり"],
   ["A good neighbor is better than a brother far off.", "遠くの親類より近くの他人 (よいご近所は遠くの兄弟よりよい)"],
   ["Soon ripe, soon rotten.", "大器晩成 (早咲きは早く消える)"],
   ["Much ado about nothing.", "大山鳴動して鼠一匹 (むなしい大騒ぎ)"],
   ["To be much of a muchness.", "どんぐりの背比べ (大同小異)"],
   ["The greater embraces the less.", "大は小を兼ねる (大きいほうに小さいほうも含まれる)"],
   ["Jack of all trades and master of none.", "器用貧乏 (多芸は無芸)"],
   ["Good company makes short miles.", "旅は道連れ世は情け (よい道連れがいれば、旅は短くなる)"],
   ["Haste makes waste.", "急いては事を仕損じる (焦りは無駄を生じる)"],
   ["Blood is thicker than water.", "血は水よりも濃し"],
   ["Strike the iron while it is hot.", "鉄は熱いうちに打て"],
   ["The nail that sticks out gets hammered in.", "出る杭は打たれる (出ている釘は打ち込まれる)"],
   ["Heaven helps those who help themselves.", "天は自ら助くる者を助く"],
   ["It's always darkest just beneath the lighthouse", "灯台下暗し"],
   ["Time is money.", "時は金（かね）なり"],
   ["Meet evil with evil.", "毒を以て毒を制す (悪には悪で立ち向かえ)"],
   ["So many countries, so many customs.", "ところ変われば品変わる (いろいろな国にいろいろな習慣がある)"],
   ["An ass in a lion's skin.", "虎の威を借りる狐 (ライオンの皮を着たロバ)"],
   ["Art is long, life is short.", "芸道は長く人生は短し"],
   ["Laughter is the best medicine.", "笑いは百薬の長 (笑いは最高の薬)"],
   ["Necessity is the mother of invention.", "必要は発明の母"],
   ["One man's fault is another man's lesson.", "人の振り見て我が振り直せ (ある人の落ち度は他の人への教訓だ)"],
   ["There's no smoke without fire.", "火のない所に煙は立たぬ"],
   ["Diligence is the mother of success.", "稼ぐに追いつく貧乏なし (勤勉は成功の母)"],
   ["Actions speak louder than words.", "不言実行 (行動は言葉より大きい)"],
   ["The pen is mightier than the sword.", "ペンは剣よりも強し"],
   ["Fine feathers make fine birds.", "馬子にも衣裳 (立派な羽毛が鳥を立派に見せる)"],
   ["Handsome is as handsome does.", "見目（みめ）より心 (立派な行いをする人こそハンサムなのだ)"],
   ["An eye for an eye, a tooth for a tooth.", "目には目を歯には歯を"],
   ["Every man knows his own business best.", "餅は餅屋 (自分の仕事は自分が一番知っている)"],
   ["Penny wise and pund foolish.", "安物買いの銭失い (ペニー（小銭）に賢く、ポンド（大金）に愚か)"],
   ["Better bend than break.", "柳に雪折れなし (壊れるくらいなら曲がったほうがよい)"],
   ["A fox is not caught twice in the same snare.", "柳の下にいつもどじょうはいない (キツネは同じ罠に二度かかることはない)"],
   ["Care killed the cat.", "心配は身の毒 (心配事で猫が死んだ)"],
   ["Speech is silver, silence is golden.", "雄弁は銀、沈黙は金"],
   ["All work and no play makes Jack a dull boy.", "よく学びよく遊べ (勉強だけして遊ばない子は鈍くなる)"],
   ["He that serves a good master shall have good wages.", "寄らば大樹の陰 (よい主に仕えればよい報酬が得られる)"],
   ["A good medicine tastes bitter.", "良薬は口に苦し"],
   ["Birds of a feather flock together.", "類は友を呼ぶ (同じ羽の鳥は共に群れる)"],
   ["The proof of the pudding is in the eating.", "論より証拠 (プリンの味は食べてみなければわからない)"],
   ["Ask, and it shall be given to you.", "求めよさらば与えられん"],
   ["The end justifies the means.", "?も方便 (結果次第で手段が正当化される)"],
   ["Every Jack has his Jill.", "割れ鍋に綴じ蓋 (どの男にも見合った女がいるものだ)"],
   ["A young idler, an old beggar.", "若い時の苦労は買ってでもせよ (若い時の怠け者は年老いて乞食)"],
   ["There's no place like home.", "我が家に勝るところなし"],
   ["Laugh and grow fat.", "笑う門には福来る (笑って太れ)"],
   ["There is no rule but has exceptions.", "例外のない規則はない"],
   ["Rome was not built in a day.", "ローマは一日にして成らず"],
   ["To cast water into the Thames.", "焼け石に水 (テムズ川に水を投げ入れるようなもの)"],
   ["A bolt from the blue.", "青天の霹靂（へきれき） (青空から稲妻)"],
   ["Like master, like man.", "この主にしてこの家臣あり"],
   ["A watched pot never boils.", "待つ身は長い (見つめられているやかんは沸かない)"],
   ["Everything comes to him who waits.", "待てば海路の日和あり (何事も待っている人のところにやってくる)"],
   ["What is learned in the cradle is carried to the grave.", "昔取った杵柄（きねづか） (ゆりかごで身につけたことは墓場まで)"],
   ["The eyes are the windows of the soul.", "目は口程に物を言う (目は心の窓)"],
   ["Give and take.", "持ちつ持たれつ (あげたりもらったり)"],
   ["Go in one ear and out the other.", "馬耳東風 (一方の耳から入り（すぐ）もう一方の耳から抜けていく)"],
   ["Well begun is half done.", "何事も始めが大事 (始めよければ半分終わったも同然)"],
   ["Pudding rather than praise.", "花より団子 (賛辞よりプリン)"],
   ["An army marches on its stomach.", "腹が減っては戦はできぬ (軍が行進するのは胃袋のおかげだ)"],
   ["Make hay while the sun shines.", "善は急げ (日が照っているうちに干し草を作れ)"],
   ["All is not gold that glitters.", "光るもの必ずしも金ならず"],
   ["Man shall not live by bread alone.", "人はパンのみにて生きるにあらず"],
   ["Poverty dulls the wit.", "貧すれば鈍する (貧困は精神も鈍くする)"],
   ["It takes two to make a quarrel.", "相手のいない喧嘩はできぬ (喧嘩をするには二人が要る)"],
   ["If Winter comes, can Spring be far behind?", "冬来たりなば春遠からじ"],
   ["He who shoots often, hits at last.", "下手な鉄砲も数撃ちゃ当たる (何度も打てば、ついには当たる)"],
   ["A barking dog seldom bites.", "弱い犬ほどよく吠える (吠える犬はめったに噛まない)"],
   ["Ploughing the field and forgetting the seeds.", "仏作って魂入れず (畑耕し種まかず)"],
   ["A man cannot give what he hasn't got.", "ない袖は振れぬ (所有してないものを与えることはできない)"],
   ["Where there is a will, there is a way.", "意志あるところに道あり"],
   ["Habit is a second nature.", "習い性（しょう）となる (習慣は第二の天性)"],
   ["Love your enemies.", "汝の敵を愛せよ"],
   ["Ill weeds grow fast.", "憎まれっ子世に憚る (雑草は伸びるのが早い)"],
   ["He who runs after two hares will catch neither.", "二兎を追う者は一兎をも得ず"],
   ["Let sleeping dogs lie.", "寝た子を起こすな (寝ている犬はそっとしておけ)"],
   ["Danger past, God forgotten.", "喉元過ぎれば熱さを忘れる (危険が去ると神を忘れる)"],
   ["The fault of another is a good teacher.", "他山の石 (他の人の落ち度はよい教訓となる)"],
   ["No man can serve two masters.", "人は二君に仕えること能わず"],
   ["Short temper causes loss.", "短気は損気 (短気は損になる)"],
   ["As different as chalk and cheese.", "月とスッポン (チョークとチーズのような（大きな）違い)"],
   ["Who spits against heaven, it falls in his face.", "自業自得 (天に唾すると自分にふりかかかる)"],
   ["Old friends and old wine are best.", "友も酒も古いがよい"],
   ["It is too late to lock the stable when the horse has been stolen.", "泥棒を捕まえて縄をなう (馬が盗まれてから馬小屋にカギをかけても遅すぎる)"],
   ["Time and tide wait for no man.", "歳月人を待たず"],
   ["He laughs best who laughs last.", "喜ぶのを早まってはいけない (最後に笑うものが最もよく笑う)"],
   ["The die is cast.", "賽は投げられた"],
   ["Take the lead, and you will win.", "先んずれば人を制す (先んずれば勝つ)"],
   ["Out of sight, out of mind.", "去る者は日日に疎し"],
   ["All's well that ends well.", "終わり良ければすべて良し"],
   ["Money makes the mare to go.", "地獄の沙汰も金次第 (金は馬をも動かせる)"],
   ["Truth is stranger than fiction.", "事実は小説より奇なり"],
   ["Politeness is not just for strangers.", "親しき中にも礼儀あり (礼儀は赤の他人のためだけのものではない)"],
   ["It’s like teaching a cat how to catch a mouse.", "釈迦に説法 (猫にネズミの捕り方を教えるようなもの)"],
   ["Take care of the pence and the pounds will take care of themselves.", "小事を軽んずるなかれ (ペニー（小銭）を大切にすればポンド（大金）は自然に集まる)"],
   ["Honesty is the best policy.", "正直は最良の策"],
   ["Doing nothing is doing ill.", "小人閑居して不善をなす (何もしないことは悪しきをなすことだ)"],
   ["The husband is always the last to know.", "知らぬは亭主ばかりなり (最後に知るのが亭主)"],
   ["Life is but an empty dream.", "人生夢のごとし (人生ははかない夢に過ぎない)"],
   ["Love begets love.", "愛は愛を生む"],
   ["More than enough is too much.", "過ぎたるは及ばざるがごとし (十分以上はあり過ぎ)"],
   ["When one door shuts, another opens.", "捨てる神あれば拾う神あり (一つのドアが閉まれば、別のドアが開く)"],
   ["All roads lead to Rome.", "すべての道はローマに通ず"],
   ["Tomorrow is a new day.", "明日は明日の風が吹く (明日は明日)"],
   ["Time flies like an arrow.", "光陰矢の如し (時は矢のごとく飛び行く)"],
   ["To lose is to win.", "負けるが勝ち (負けることは勝つことだ)"],
   ["Out of the mouth comes evil.", "口は災いの元 (災いが口から出る)"],
   ["The more, the merrier.", "枯れ木も山の賑わい (人数が多ければそれだけ楽しい)"],
   ["Offense is the best defense.", "攻撃は最大の防御"],
   ["Go for broke.", "当たって砕けろ (有り金をはたく)"],
   ["Speak of the devil and he will appear.", "噂をすれば影 (悪魔のうわさをすると、悪魔が現れる)"],
   ["Sleep and wait for good luck.", "果報は寝て待て (眠って幸運を待て)"],
   ["You cannot be too careful.", "念には念を入れよ (注意のし過ぎはない)"],
   ["Names and natures do often agree.", "名は体を表す (名前と性質は一致することが多い)"],
   ["Money comes and goes.", "金は天下の回り物 (金は出たり入ったりだ)"],
   ["Might makes right.", "無理が通れば道理引っ込む (力が正義を作り出す)"],
   ["Losers are always in the wrong.", "勝てば官軍負ければ賊軍 (敗者は常に悪者に)"],
   ["Looks can be deceiving.", "人は見かけによらぬもの (外見は当てにならない)"],
   ["Look before you leap.", "転ばぬ先の杖 (飛ぶ前に見よ)"],
   ["Liars should have good memories.", "?つきの必需品は記憶力"],
   ["Know thyself [yourself].", "汝自身を知れ"],
   ["You can never be too prepared.", "備えあれば憂いなし (準備のし過ぎはない)"],
   ["Too much for one thing and too litle for the other.", "帯に短し、たすきに長し (これには多過ぎ、あれには少な過ぎ)"],
   ["Things depend on how you look at them.", "物は考えよう (物事は見方による)"],
   ["Spare the rod and spoil the child", "可愛い子には旅をさせよ (鞭を惜しむと子供をだめにする)"],
   ["Home is home however humble it may be.", "住めば都 (いかに貧しくとも家は家)"],
   ["He that knows little often repeats it.", "馬鹿の一つ覚え (知識のない人はそれだけを繰り返す)"],
   ["A bargain 's a bargain.", "約束は約束"],
   ["A burnt child dreads the fire.", "火傷したこどもは火を怖がる"],
   ["A cat has nine lives.", "猫に九生あり (猫には九つの命がある)"],
   ["A cock is bold on his own dunghill.", "内弁慶 (雄鶏は自分の糞の上では勇敢だ)"],
   ["A constant guest is never welcome.", "いつも来る客は歓迎されない（ものだ）"],
   ["A drowning man will catch at a straw.", "溺れる者は藁をもつかむ"],
   ["Yesterday's enemy is today's friend.", "昨日の敵は今日の友"],
   ["A good wife makes a good husband.", "この妻にしてこの夫あり (良妻は良夫を作る)"],
   ["A good husband makes a good wife.", "この夫にしてこの妻あり (良夫は良妻を作る)"],
   ["A good name is better than riches.", "名声は富に勝る"],
   ["A heavy purse makes a light heart.", "財布が重いと心は軽い"],
   ["A little pot is soon hot.", "小人怒りやすし (小さなやかんはすぐ熱くなる)"],
   ["A living dog is better than a dead lion.", "命あっての物種 (死んだライオンより生きている犬のほうがましだ)"],
   ["All cats are grey in the dark.", "一皮むけばみな同じ (猫は暗闇の中ではみな灰色)"],
   ["A man away from home need feel no shame.", "旅の恥は?き捨て (故郷を離れた男は恥を感じる必要がない)"],
   ["A man is known by the company he keeps.", "人（柄）はその仲間によって分かる"],
   ["A man may lead a horse to the water，but he cannot make him drink.", "最後の決断は（他人ではなく）自分 (馬を水辺に連れていくことはできるが、水を飲ませることはできない)"],
   ["A man without a wife is but half a man.", "妻のいない男は半人前"],
   ["A sound mind in a sound body.", "健全な身体に健全な精神"],
   ["Brevity is the soul of wit.", "言は簡潔を尊ぶ (簡潔は知恵の真髄だ)"],
   ["Cast not pearls before swine.", "猫に小判 (豚に真珠を投げてはいけない)"],
   ["Charity begins at home.", "慈愛はまず家庭から"],
   ["Dead men tell no lies.", "死人に口なし (死人はうそをつかない)"],
   ["Even the walls have ears.", "壁に耳あり"],
   ["Fortune comes in at the merry gate.", "笑う門には福来る"],
   ["Honesty does not pay.", "正直者が馬鹿を見る (正直は割に合わない)"],
   ["Nothing costs so much as what is given us.", "ただより高い物はない (もらいものほど高くつくものはない)"],
   ["Repentance comes too late.", "後悔先に立たず (遅過ぎる悔恨)"],
   ["A picture is worth a thousand words.", "聞くは見るに及ばず (1枚の写真は１００の言葉と同じ価値)"],
   ["Beauty is in the eye of the beholder.", "美は見る人次第 (美は見る人の目にある)"],
   ["Cleanliness is next to godliness.", "きれい好きは美徳 (清潔は信心に次ぐ)"],
   ["Don’t bite the hand that feeds you.", "恩を仇で返すな (食事を与えてくれる人の手を?むな)"],
   ["If you play with fire, you'll get burned.", "火遊びはけがの元 (火遊びをするとやけどする)"],
   ["No man is an island.", "人は一人で生きられない (人は誰も島ではない)"],
   ["People who live in glass houses should not throw stones.", "己の欲せざるところ人に施すことなかれ (カラスの家に住む者は石を投げるべからず)"],
   ["A fool at forty is a fool indeed.", "40歳のばかは本物のばか"],
   ["A man is a fool or a physician at thiry.", "三十にして立つ(30歳になれば馬鹿か医者のどちらかだ)"],
   ["A stitch in time saves nine.", "今日の一針、明日の九針"],
   ["First impressions are the most lasting.", "第一印象はなかなか消えない"],
   ["Fish and guests stink after three days.", "珍客も3日いれば鼻につく(魚と客は3日経つと鼻につく)"],
   ["The squeaky wheel gets the grease.", "主張すれば聞かれる(きしむ車輪は油をさされる)"],
   ["Genius is one percent inspiration and ninety-nine percent perspiration.", "天才とは直感1パーセント、努力が99パーセント"],
   ["Give him an inch, and he'll take a mile.", "寸を与えれば尺を望む / おんぶすれば抱っこ(1インチ与えると、1マイルを取りたがるもの)"],
   ["It needs more skill than I can tell to play the second fiddle well.", "脇役こそ偉大な務め(第二バイオリンをうまく弾くには言葉に表せない技量が必要)"],
   ["A bully is always a coward.", "弱い者いじめはみな臆病者"],
   ["Lean liberty is better than fat slavery.", "太った豚より痩せたソクラテス(やせた自由は太った奴隷よりまし)"],
   ["All his geese are swans.", "自画自賛(自分のダチョウはみな白鳥)"],
   ["Cut your coat according to your cloth.", "分相応の生活をせよ(生地に合わせて裁断せよ)"],
   ["Better an egg today than a hen tomorrow.", "明日の百より今日の五十(明日の雌鶏より今日の卵)"],
   ["Better be the head of a dog than the tail of a lion.", "鶏口となるも牛後となるなかれ(ライオンのしっぽより犬の頭がよい)"],
   ["Big fish eat little fish.", "弱肉強食(大魚が小魚を食う)"],
   ["Two blacks do not make a white.", "悪で悪を上塗りできぬ(黒で黒を消すことはできない)"],
   ["There's a black sheep in every flock.", "どこにも厄介者はいるもの(どの群れにも黒い羊がいる)"],
   ["Dead men tell no tales.", "死人に口なし"],
   ["The devil is not so black as he is painted.", "鬼のなかにも仏がいる(悪魔も描かれているほど黒くはない)"],
   ["Pride feels no pain.", "見栄っ張りに苦痛なし"],
   ["Save for a rainy day.", "備えあれば患いなし(雨の日に備えよ)"],
   ["See no evil, hear no evil, speak no evil.", "見ざる聞かざる言わざる(悪を見るな、聞くな、語るな)"],
   ["Set a thief to catch a thief.", "蛇の道は蛇(泥棒を捕えるには泥棒を使え)"],
   ["Slow and steady wins the race.", "急いては事を仕損じる(ゆっくり着実が競走に勝つ)"],
   ["Proper praise stinks.", "自賛は悪臭を放つ"],
   ["The belly has no ears.", "空腹に耳なし(腹が減ると何も耳に入らない)"],
   ["The best of friends must part.", "会うは別れの始め(最良の友ともいつかは別れはくる)"],
   ["The busiest men have the most leisure.", "多忙も時間の使いよう(最も多忙な人が最も暇をもっている)"],
   ["There's no fool like an old fool.", "老い木に花(年寄の夢中はどうしようもない)"],
   ["To err is human, to forgive, divine.", "過つは人の常，許すは神のわざ"],
   ["Want is the mother of industry.", "困窮は勤勉の母"],
   ["One man's meat is another man's poison.", "十人十色(ある人にとっての肉は別の人の毒)"],
   ["Nothing is certain but the unforeseen.", "先のことはわからない(予想外のことを除き、人生に確実なものはない)"],
   ["New brooms sweep clean.", "新人はよく働く(新しい箒はきれいに掃ける)"],
   ["Never trouble trouble till trouble troubles you.", "取り越し苦労は無用(心配は心配事が起きてからに)"],
   ["Never speak ill of the dead.", "死者に鞭打つな(死者の悪口を言ってはいけない)"],
   ["Never do things by halves.", "中途半端をしてはならぬ"],
   ["He who would climb the ladder must begin at the bottom.", "千里の道も一歩より(梯子登りは最下段から始まる)"],
   ["Home is where the heart is.", "故郷とは心の宿る場所"],
   ["Never look a gift horse in the mouse.", "もらいものにケチをつけるな(もらった馬の口を見て値踏みしてはならぬ)"],
   ["The cat would eat fish but would not wet her feet.", "河豚は食いたし命は惜しし(猫は魚を食いたし、足を濡らしたくなし)"],
   ["The higher the monkey climbs the more he shows his tail.", "桂馬の高上り歩の餌食(猿が高く登るほどよけいしっぽを見せる)"],
   ["A bad workman always blames his tools.", "下手の道具調べ(下手な職人は道具のせいにする)"],
   ["One good turn deserves another.", "情けは人の為ならず(一つの善行はもう一つの善行をもたらす)"],
   ["Manners know distance.", "親しき仲にも礼儀あり(礼儀は距離をわきまえている)"],
   ["Patience is a virtue.", "忍耐は美徳なり"],
   ["Much caution does no harm.", "石橋を叩いて渡る(注意を怠らなければ被害なし)"],
   ["Stoop to conquer.", "負けて勝つ(勝つためには身をかがめよ)"],
   ["Bread is better than the songs of birds.", "花より団子(鳥のさえずりよりパン)"],
   ["More haste, less speed.", "急がば回れ(急ぐならゆっくりと)"],
   ["What is done cannot be undone.", "後悔先に立たず(やってしまったことはやらなかったことにできない)"],
   ["All things are obedient to money.", "この世はすべて、金が幅を利かせる"],
   ["When the cat is away, the mice will play.", "鬼の居ぬ間の洗濯(猫がいない間、ネズミが遊ぶ)"],
   ["Fools rush in where angels fear to tread.", "飛んで火にいる夏の虫(愚か者は天使の恐れるところにも飛び込む)"],
   ["The child is father to the man.", "三つ子の魂百まで(子どもは大人の父)"],
   ["Fear is often greater than the danger.", "案ずるより産むがやすし(危険そのものは恐れたほどひどくないことが多い)"],
   ["Good wine makes good blood.", "酒は百薬の長(よいワインはよい血液を作る)"],
   ["None but the brave deserves the fair.", "勇者にあらずんば美女を得ず"],
   ["A black hen lays a white egg.", "鳶が鷹を産む(黒い雌鶏が白い卵を産む)"],
   ["Clothes make the man.", "馬子にも衣裳(服装が人を作る)"],
   ["Honesty is ill for thriving.", "正直者が馬鹿を見る(正直は繁栄の足かせだ)"],
   ["Who can read the future?", "一寸先は闇(誰にも未来は読めない)"],
   ["Security is the greatest enemy.", "油断大敵(安心は最大の敵)"],
   ["Opportunity makes the thief.", "油断大敵(隙を与えると盗まれる)"],
   ["Bad luck often brings good luck.", "災い転じて福となす(不運が幸運をもたらすこともよくあるものだ)"],
   ["Joy and sorrow are next door neighbors.", "喜びと悲しみは隣りあわせ"],
   ["Example is better than precept.", "論より証拠(実例は教訓に勝る)"],
   ["A book that remains shut is but a block.", "宝の持ち腐れ(閉じたままの本はただの塊)"],
   ["Unused treasure is a waste of treasure.", "宝の持ち腐れ(宝も使わなければ無駄物)"],
   ["One man’s trash is another man’s treasure.", "人それぞれ(ある人にとってのごみも別の人にとっての宝)"],
   ["Death is the great leveler.", "死は万人を平等にする"],
   ["Do as I say, not as I do.", "私の言うことを守り、行いはまねるな"],
   ["Do not spur a willing horse.", "駿馬に鞭打つな(自ら進んで進む馬に鞭打つな)"],
   ["Don't cross the bridge until you come to it.", "取り越し苦労はするな(橋に着く前に橋を渡る必要はない)"],
   ["Don't quarrel with your bread and butter.", "生業に文句をつけるな"],
   ["Don't take your harp to the party.", "一つ覚えを繰り返すな(パーティーに自分の竪琴をもって行くな)"],
   ["Early to bed and early to rise makes a man healthy, wealthy and wise.", "早寝早起きは人を健康で裕福で賢明する"],
   ["East or west, home is best.", "どこへ行こうとも、我が家が一番"],
   ["Empty vessels make the most sound.", "能なしの口たたき(からの容器ほど大きい音を立てる)"],
   ["Every ass likes to hear itself bray.", "人は自分のことをしゃべりたがる(どのロバも自分の鳴き声を聞きたがる)"],
   ["Every flow must have its ebb.", "栄枯盛衰は世の習い(満ち潮があれば、引き潮もある)"],
   ["Everybody's business is nobody's business.", "共同責任は無責任(全員の責任はだれの責任でもない)"],
   ["Up corn, down horn.", "穀物高騰の時は肉の価格は下がる"],
   ["Two of a trade never [seldom] agree.", "商売敵は気が合わぬ"],
   ["Nature is the best physician.", "自然は最良の医師"],
   ["Union is strength.", "団結は力なり"],
   ["Too much water drowned the miller.", "過ぎたるはなお及ばざるが如し(大量の水で（水車）粉屋が溺れた)"],
   ["Tomorrow is another day.", "明日は明日の風が吹く(明日はまた新しい日だ)"],
   ["Whom the gods love die young.", "佳人薄命(神々に愛されるものは短命だ)"],
   ["Third time does the trick.", "三度目の正直(三度目はうまくいく)"],
   ["They brag most who can do least.", "無能者ほど大口をたたく(一番できないやつが一番大口をたたく)"],
   ["There is safety in numbers.", "大勢いれば怖くない(多数の中に安全がある)"],
   ["Neither a borrower nor a lender be.", "金の貸し借りをしてはならぬ(借り手にも貸し手にもなるな)"],
   ["Never confuse art with life.", "絵に描いた餅は食えない(芸術と生活を混同してはならない)"],
   ["Never hesitate to do what you think is right.", "善は急げ(正しいと思うことは迷わず実行せよ)"],
   ["Never spend your money before you have it.", "金は入ってから使え(お金が入る前に使ってはならぬ)"],
   ["It's never too late to mend.", "過ちを改むるにはばかることなかれ"],
   ["Next year is the devil's joke.", "来年の事を言えば鬼が笑う(来年は悪魔の冗談)"],
   ["No fish is caught twice with the same bait.", "二度と同じ手は食わぬ(同じ餌に二度引っかかる魚はいない)"],
   ["Love sees no faults.", "痘痕も靨(愛する人の欠点は見えない)"],
   ["Each goes to hell in his own way.", "京の着倒れ大阪の食い倒れ(地獄行きも人それそれ)"],
   ["Even a broken clock is right twice a day.", "馬鹿にも一芸(壊れた時計も一日に2度は正確)"],
   ["Even the best swimmer sometimes gets drowned.", "河童の川流れ(泳ぎの名手も溺れることあり)"],
   ["Every cock crows on its own dunghill.", "内弁慶は誰でもできる(どのカラスも自分の糞の上ではよく鳴く)"],
   ["Every man has his humor.", "十人十色(人はそれぞれの気質を持っているものだ)"],
   ["There are two sides to every question.", "物事には二面があるものだ"],
   ["Every why has a wherefore.", "何事にも理由はあるもの"],
   ["Last come, last served.", "先着順(最後に来た人は最後尾に)"],
   ["Lend your money and lose your friend.", "金の切れ目が縁の切れ目(金を貸すと友を失う)"],
   ["Let beggars match with beggars.", "割れ鍋に綴じ蓋(乞食の相棒は乞食に)"],
   ["Let bygones be bygones.", "過ぎしことは過ぎしこと"],
   ["Gather roses while you may.", "できるうちに青春を楽しめ(できるうちに薔薇を集めよ)"],
   ["Genius displays itself even in childhood. ：", "栴檀（せんだん）は双葉（ふたば）より芳し(天才は幼少時より才能を発揮する)"],
   ["Gluttony kills more than the sword.", "大食短命 / 腹八分目に医者いらず(暴食は剣よりも多くの人を死に至らしめる)"],
   ["Good deeds should be done quickly.", "善は急げ"],
   ["Good fences make good neighbors.", "親しき中にも礼儀あり(よい垣根がよい隣人を作る)"],
   ["Good news goes on crutches.", "好事門を出でず(よい知らせは松葉杖をついて行く)"],
   ["Good watch prevents misfortune.", "転ばぬ先の杖(気をつけることで不幸が防げる)"],
   ["Good wine needs no bush.", "良酒に看板は要らぬ(良酒はツタに看板を掛ける必要がない)"],
   ["Grasp all, lose all.", "大欲は無欲に似たり / 二兎を追う者は一兎をも得ず(すべてをつかもうとすれば、すべてを失う)"],
   ["Great minds think alike.", "偉人は等しく思う。まるで君と僕だね。(（考えが一致した時に言う）)"],
   ["Great pains but all in vain.", "骨折り損のくたびれ儲け"],
   ["Great talkers are little doers.", "口自慢の仕事下手"],
   ["Half a loaf is better than none.", "パン半分でもないよりはまし"],
   ["Hang sorrow, cast away care.", "悲しみも取り越し苦労も投げ捨てよう"],
   ["Harm watch harm catch.", "災いに目を向けていると災いに遭う"],
   ["He cannot speak well that cannot hold his tongue.", "舌を慎めないものはうまく語れない"],
   ["He is rich that has few wants.", "足るを知る者は富める者(多くを望まない者が富者だ)"],
   ["He that cannot obey cannot command.", "服従できない者は命令者になれない"],
   ["He travels the fastest who travels alone.", "一人旅が一番速い"],
   ["He who carries nothing loses nothing.", "持たざる者、失う物なし"],
   ["He who gives to the poor, lends to the Lord.", "情けは人の為ならず(貧者に施すものは主なる神に功徳を積むことになる)"],
   ["He who hesitates is lost.", "二の足を踏む者は機を逸する(ためらうものは負ける)"],
   ["He who makes no mistakes makes nothing.", "失敗なくして何もできない"],
   ["Health is above wealth.", "健康は富に勝る"],
   ["Hoist your sail when the wind is fair.", "得手（えて）に帆を揚げよ / 好機を逃すな(順風の時に帆を揚げよ)"],
   ["Honest men marry soon, wise men not at all.", "正直男は早婚、賢い男は独身"],
   ["Hope for the best and prepare for the worst.", "最善を祈り、最悪に備えよ"],
   ["Hunger has no law.", "背に腹は代えられない(空腹に法律はない)"],
   ["Pity is akin to love.", "恋と哀れみは隣りあわせ(哀れみは恋愛と同種だ)"],
   ["Knowledge is power.", "知（識）は力なり"],
   ["Care follows wealth.", "金持ちは気苦労が多い(富には心配が伴う)"],
   ["Cast not the first stone.", "罪なき者まず石を投げよ(最初の石を投げるな。その前に自分を反省せよ。)"],
   ["Christmas comes but once a year.", "（クリスマスは年に一度しか来ない）大いに楽しめ"],
   ["Circumstances may justify a lie.", "?も方便(事情によって嘘も正当化される)"],
   ["Claw me, and I'll claw thee [you].", "魚心あれば水心(掻いてください、私も掻いてあげるから)"],
   ["Scratch my back and I’ll scratch yours.", "魚心あれば水心(背中を掻いてください、私も掻いてあげるから)"],
   ["Clouds always follow the sunshine.", "好事魔多し(日照りの後は必ず曇り)"],
   ["Lying and stealing are next-door neighbors.", "うそつきは泥棒の始まり(うそつきと泥棒は隣りあわせ)"],
   ["Love your neighbor, yet pull not down your fence.", "親しき中にも礼儀あり(隣人を愛せよ、されど垣根は取り払うな)"],
   ["Love can cure anything.", "愛こそ万能薬(愛は何でも治す)"],
   ["Money begets money.", "金が金を産む"],
   ["Onlookers see more than the players.", "岡目八目(観客はプレイヤー以上に見ている)"],
   ["Constant dropping wears the stone.", "点滴岩をも穿つ(雫も続けば岩をも穿つ)"],
   ["Less is more.", "過ぎたるは猶及ばざるが如し(少なすぎるのは多すぎるのと同じだ)"],
   ["Lead the way by setting an example.", "隗（かい）より始めよ"],
   ["Keep your shop and your shop will keep you.", "商いは牛の涎（のように細く長く）(店を守り続けよ、そうすれば店があなたを守ってくれる)"],
   ["Idle folk have the least leisure.", "怠け者ほど暇がない"],
   ["Idleness is the mother of all evil.", "小人閑居して不善をなす(怠惰は諸悪の母)"],
   ["Whatever is worth doing at all, is worth doing well.", "いやしくもやる価値のあるものは、うまくやる価値がある"],
   ["If it were not for hope, the heart would break.", "望みなきとき、心は裂ける"],
   ["If wishes were horses, beggars might ride.", "ままにならぬが浮世の常(望むだけで馬が手に入るなら、乞食でも馬に乗れる)"],
   ["If you can’t fight them, join them.", "長い物には巻かれよ(勝ち目がなければ、加担せよ)"],
   ["If you love your child, send him out on a journey.", "可愛い子には旅をさせよ"],
   ["Condemn the offense, but pity the offender.", "罪を憎んで人を憎まず(罪は咎めても、罪人には憐れみを)"],
   ["Ill got, ill spent.", "悪銭身につかず(不正に得た金は乱費される)"],
   ["Inscrutable are the ways of Heaven.", "人間万事塞翁が馬(天のやり方は不可解)"],
   ["It is better to give than to receive.", "受くるより与うるが幸いなり"],
   ["It is an ill wind that blows nobody good.", "風が吹けば桶屋が儲かる(誰のためにもならない風は吹かない)"],
   ["Hunger never saw bad bread.", "空腹にまずいものなし(空腹はまずいパンを見たことがない)"],
   ["It is a long lane that has no turning.", "待てば海路の日和あり(どんな長い道もどこかに曲がり角があるはず)"],
   ["It is too late to call back yesterday.", "後の祭り(きのうを呼び戻そうとしても遅すぎる)"],
   ["It never rains but it pours.", "弱り目に祟り目(降れば必ず土砂降り)"],
   ["It will be a nine day’s wonder.", "人のうわさも75日(驚きも９日間しか続かない)"],
   ["Zeal without knowledge is a runaway horse.", "生兵法は大怪我の基(知識を伴わない熱情は逃げ出した馬のようなものだ)"],
   ["Yield to the powerful.", "長い物には巻かれよ(力ある者には屈せよ)"],
   ["You cannot burn the candle at both ends.", "心は一つ身は二つ(ろうそくを両端から燃やすことはできない)"],
   ["You cannot catch old birds with chaff.", "老練者を簡単にだますことはできない(老いた鳥をもみ殻で捕まえることはできない)"],
   ["You cannot eat your cake and have it.", "二つよいことはない(ケーキを食べればもう残ってはいない)"],
   ["You cannot make an omelet without breaking eggs.", "蒔かぬ種は生えぬ(卵を割らないでオムレツを作ることはできない)"],
   ["You can't see the forest for the trees.", "木を見て森を見ず"],
   ["You may go farther and fare worse.", "中庸の徳(進み過ぎると成り行きが悪くなる)"],
   ["You never forget your own trade.", "昔取った杵柄(自分でやってきた商いを忘れることはない)"],
   ["The fish you lose is always the biggest.", "逃がした魚は大きい"],
   ["You'll never know unless you try.", "物は試し(何事もやってみなければわからない)"],
   ["Youth will be served.", "若い時はもてるもの"],
   ["We may sleep in the same bed, but we have different dreams.", "同床異夢"],
   ["Well fed, well bred.", "衣食足りて礼節を知る(食が足りていれば、育ちもよくなる)"],
   ["What can’t be cured must be endured.", "諦めが肝心(癒せないものは我慢せねばならない)"],
   ["Bad money drives out good.", "悪貨は良貨を駆逐する"],
   ["Take your chance.", "当たって砕けろ"],
   ["What happens twice will happen three times.", "二度あることは三度ある"],
   ["What is bred in the bone will not go out of the flesh.", "三つ子の魂百まで(骨までしみ込んだ育ちは肉の外に出ていくことはない)"],
   ["What the heart thinks, the mouth speaks.", "思いは口に出る(心が思ったことは、口が話す)"],
   ["What you don't know can't hurt you.", "知らぬが仏(自分が知らないことで心が痛むことはない)"],
   ["If the sky fall, we shall catch larks.", "取り越し苦労は無用(空が落ちれば雲雀がとれる)"],
   ["When in doubt, leave out.", "疑わしきときは取り上げるな（書くな）"],
   ["When the word is out, it belongs to another.", "一度口に出したことは取り返しがつかない(一度口に出したことばはもう他人の物)"],
   ["Love conquers all.", "愛はすべてに打ち勝つ"],
   ["A lie travels round the world while truth is putting her boots on.", "悪事千里を走る(真実が靴を履いている間に虚言は世界中を駆け巡っている)"],
   ["Growing old is mandatory. Growing up is optional.", "「老化」は必然。「成長」は人それぞれ"],
   ["Wise men don't need advice. Fools won't take it.", "賢者は忠言を要せず。愚人は忠言を受け入れず"],
   ["There is nothing permanent except change.", "変化ほど永劫なるものなし"],
   ["When you're thirsty, it's too late to think about digging a well.", "渇(かつ)に臨みて井を穿(うが)つ(喉が渇いてから井戸を掘っても遅すぎる)"],
   ["Choose your wife as you wish your children to be.", "わが子がそうなってほしいような人を妻に向かえよ"],
   ["There is no difference between a wise man and a fool when they fall in love.", "恋に落ちれば賢者も愚人もみな同じ"],
   ["The woman cries before the wedding and the man after.", "女は嫁ぐ前に泣き、男は嫁がれた後に泣く"],
   ["Don't bite off more than you can chew.", "身の丈を知るべし(自分で噛める以上を食してはならぬ)"],
   ["Love never dies.", "愛は永遠(愛は決して死なない)"],
   ["There are no birds in last year's nest.", "柳の下にいつもドジョウはおらぬ(去年いた巣に鳥はおらぬ)"],
   ["It's always darkest before the dawn.", "明けない夜はない(夜明け前が一番暗い)"],
   ["cry wine and sell vinegar", "羊頭狗肉 / 看板に偽りあり(ワインと言って酢を売る)"],
   ["A good tree is a good shelter.", "寄らば大樹の陰(立派な樹はよい避難場所になる)"],
   ["The grapes are sour.", "負け惜しみの減らず口(あのブドウは酸っぱい)"],
   ["Marry in haste, and repent at leisure", "あわてて結婚ゆっくり後悔"],
   ["The biter is sometimes bit.", "因果応報(噛む者は時に噛まれる)"],
   ["Water seeks its own level.", "人は安易に流れる(水は低きに流る)"],
   ["The boughs that bear most hang lowest.", "実るほど頭が下がる稲穂かな(多くの実をつけた枝ほど低く垂れる)"],
   ["Might is right.", "無理が通れば道理引っ込む(力が正義)"],
   ["Smooth words make smooth ways.", "物は言いようで角が立つ(なめらかな言葉はなめらかな道を開く)"],
   ["A fool's bolt is soon shot.", "愚者は浅知恵(愚者はすぐ矢を放つ)"],
   ["Don't put all your eggs in one basket.", "一つのものにすべてをかけるな / リスクを分散せよ(全部の卵を一つのかごに入れるな)"],
   ["Many hands make light work .", "人手が多いと仕事が楽"],
   ["Learn from the follies of others.", "人の振り見て我が振り直せ(人の愚行から学べ)"],
   ["Man is a wolf to man.", "人を見たら泥棒と思え(人にとって人は狼だ)"],
   ["We piped for you and you did not dance.", "笛吹けど踊らず"],
   ["Eagles eat no flies.", "武士は食わねど高楊枝(鷲は蠅を食わぬ)"],
   ["It would make a horse laugh.", "臍が茶を沸かす(馬でも笑う（ほど面白い）)"],
   ["Love me, love my dog.", "坊主憎けりゃ袈裟まで憎い（の対表現）(私を愛するなら、私の犬も愛して)"],
   ["He has brought up a bird to pick out his own eyes.", "飼い犬に手を?まれる(育てた鳥に目を突っつかれる)"],
   ["A tempest in a teapot.", "蝸牛（かぎゅう）角上（かくじょう）の争い(コップの中の嵐（のように小さな社会でのもめごと）)"],
   ["A storm in a glass of water.", "蝸牛（かぎゅう）角上（かくじょう）の争い(コップの水の中の嵐（のように小さな社会でのもめごと）)"],
   ["Experience without learning is better than learning without experience.", "学問なき経験は経験なき学問にまさる"],
   ["having an itch that one cannot scratch", "隔靴?痒（かっかそうよう）(掻けないところがかゆい)"],
   ["Never halloo till you are out of the woods.", "危険が完全に去るまで喜ぶな(森を抜けだすまで大声を上げるな)"],
   ["Every miller draws water to his own mill.", "我田引水(水車粉屋はみな自分のところに水を引く)"],
   ["Out of pocket, out of mind.", "金の切れ目が縁の切れ目(お金が消えると忘れ去られる)"],
   ["Sadness and gladness succeed each other.", "禍福（かふく）は糾（あざな）える縄の如し(悲しみと喜びは交互に来る)"],
   ["Call no man great before he is dead.", "棺を蓋いて事定まる(死ぬ前にその人を偉人と呼ぶな)"],
   ["Nothing is lost for asking.", "聞くは一時の恥聞かぬは一生の恥(聞いて失う物は何もない)"],
   ["A drop in a bucket.", "九牛の一毛(バケツの中の一滴（のようにささいなこと）)"],
   ["Any port in a storm.", "窮余の策(嵐の時は（とりあえず）どこでも港に)"],
   ["Forbidden fruit is sweetest.", "怖いもの見たさ(禁断の実は甘い)"],
   ["No cross, no crown.", "苦あれば楽あり(十字架なくして冠なし)"],
   ["Better be safe than sorry.", "君子危うきに近寄らず(後悔するより安全を先に)"],
   ["A wise man changes his mind, a fool never.", "君子豹変す(賢者は心変わりするが、愚人は変わらない)"],
   ["Experience is the best teacher.", "経験は最良の師"],
   ["Little and often fills the purse.", "塵も積もれば山となる(少しずつでも頻繁に続ければ財布が膨れる)"],
   ["Time has wings.", "光陰矢の如し(時（間）には羽が生えている)"],
   ["The tailor's wife is worst clad.", "紺屋（こうや）の白袴(仕立て屋の嫁はひどい服装)"],
   ["A horse may stumble though it has four legs.", "弘法も筆の誤り(四本足の馬でさえ転ぶことがある)"],
   ["Don't ask for trouble.", "触らぬ神に祟りなし(（わざわざ）厄介を求めるな)"],
   ["The best thing to do now is to run away.", "三十六計逃げるに如かず(今やるべき最善は逃げることだ)"],
   ["Within a little head, great wit.", "山椒は小粒でもぴりりと辛い(小さな頭に大きな知識)"],
   ["A little body often harbors a great soul.", "山椒は小粒でもぴりりと辛い(小さな体にも大きな心が宿ることが多い)"],
   ["No penny, no pardon.", "地獄の沙汰も金次第(金がなければ許しももらえぬ)"],
   ["A hedge between keeps friendship green.", "親しき仲にも礼儀あり(垣根が友情を新鮮に保つ)"],
   ["He that knows nothing doubts nothing.", "知らぬが仏(何も知らぬものは何も疑わぬ)"],
   ["One of these days is none of these days.", "「そのうちいつか」は決して来ない"],
   ["Do the likeliest, and God will do the best.", "人事を尽くして天命を待つ(できる限りを尽くしなさい。そうすれば神が最善を成して下さる)"],
   ["Don’t make a mountain out of a molehill.", "針小棒大（はよせ）(モグラ塚ほどのことを山のように言うな)"],
   ["A chance acquaintance is a divine ordinance.", "袖すりあうも他生の縁(偶然の出会いは神の摂理)"],
   ["Lay up for a rainy day.", "備えあれば患いなし(雨の日に備えて蓄えよ)"],
   ["Sometimes the best gain is to lose.", "損して得取れ(失うことが最大の得になることもある)"],
   ["The mountains have brought forth a mouse.", "大山鳴動して鼠一匹"],
   ["To see it rain is better than to be in it.", "高みの見物(雨が降るのを見るのは雨に濡れるより楽だ)"],
   ["Many dogs may easily worry one.", "多勢に無勢(多くの犬が一匹の犬を怖がらせるのは簡単だ)"],
   ["Who will bell the cat?", "誰が難題を引き受けるか（それが問題だ）(誰が猫に鈴をつけるか？)"],
   ["Good advice is harsh to the ear.", "忠言耳に逆らう(よい忠言は耳に痛い)"],
   ["A tall tree catches much wind.", "出る杭は打たれる(高い樹は風に打たれる)"],
   ["Misery loves company.", "同病相憐れむ(みじめなものは友を求める)"],
   ["It is like beating the air.", "豆腐にかすがい(空気を殴っているようなもの)"],
   ["He that hath wife and children hath given hostages to fortune.", "子は三界の首枷（くびかせ）(妻子ある者、運命に人質を取られたかの如し)"],
   ["He that hath a full purse never wanted a friend.", "金持ち友に不足せず"],
   ["Wedlock is a padlock.", "婚姻は身の枷（かせ）"],
   ["All is fish that comes to the net.", "転んでもただでは起きぬ(網にかかるものはみな魚)"],
   ["Procrastination is the thief of time.", "思い立ったが吉日(ためらいは時間泥棒)"],
   ["The sting of a reproach is the truth of it.", "頂門の一針(とがめが痛いのはそのとがめが正しいことだ)"],
   ["Wine in, truth out.", "酒が入ると本音が出る"],
   ["Truth will out.", "真実はいずれ明らかになる"],
   ["God's mill grinds slow but sure.", "天網恢恢（かいかい）疎（そ）にして漏らさず(神の臼はゆっくり確実に回る)"],
   ["Holding a candle to the devil.", "盗人に追い銭（おいせん）(悪魔のためにろうそくを灯す)"],
   ["Kings have long arms.", "泣く子と地頭には勝てない(王たちの腕は長い（ので、どこまでもとどく）)"],
   ["A kindness is never lost.", "情けは人の為ならず(親切が消えてなくなることはない)"],
   ["A little knowledge is a dangerous thing.", "生兵法（なまびょうほう）は大怪我の基(わずかな知識は危険だ)"],
   ["See Naples and then die.", "日光を見ずして結構と言うな(死ぬ前にナポリを見よ)"],
   ["Never twice without three times.", "二度あることは三度ある"],
   ["A man cannot whistle and drink at the same time.", "二兎を追う者は一兎をも得ず(口笛を吹きながら飲み物を飲むことはできない)"],
   ["Good luck lies in odd numbers.", "残り物には福がある(幸運は奇数にある)"],
   ["One swallow does not make a summer.", "早合点は禁物(燕が一羽来たとて夏が来たことにはならない)"],
   ["There is no rose without a thorn.", "薔薇にとげあり"],
   ["Temperance is the best physic.", "節制は最良の薬"],
   ["People will talk.", "人の口に戸は立てられぬ"],
   ["A candle flickering before the wind.", "風前の灯火（ともしび）"],
   ["Deeds, not words.", "不言実行"],
   ["A man's word is as good as his bond.", "武士に二言はない(男の約束は証文と同じ)"],
   ["Don't put the cart before the horse.", "本末転倒（をするな）(馬の前に荷車を置くな)"],
   ["Gluttons dig their graves with their teeth.", "大食短命(大食漢は自分の歯で墓穴を掘る)"],
   ["An ill life, an ill end.", "身から出た錆(よくない生き方はよくない最期をもたらす)"],
   ["Today a king, tomorrow nothing.", "槿花（きんか）一朝（いっちょう）の夢 / 三日天下(今日の王様、明日の凡人)"],
   ["Soon hot, soon cold.", "三日坊主(熱しやすきは冷めやすし)"],
   ["When might is master, justice is servant.", "無理が通れば道理引っ込む(力が主人になると、正義は召使となる)"],
   ["It's six of one and a half dozen of the other.", "五十歩百歩 / どっちもどっち(ある人にとっての6は他の人にとっての半ダースだ)"],
   ["The eyes have one language everywhere.", "目は心の鏡(目はどこにおいても一つの言葉しか持ってない)"],
   ["A creaking gate hangs long.", "柳に雪折れなし(軋る門は長持ちする)"],
   ["A stick out of a thicket.", "藪から棒"],
   ["Fancy may kill or cure.", "病は気から(死ぬも治るも気分次第)"],
   ["There is no pleasure without pain.", "楽あれば苦あり(苦しみなくて愉しみはない)"],
   ["Heavy work in youth is quiet rest in old age.", "若い時の苦労は買ってでもせよ(若い時の重労働は老年の安穏（につながる）)"],
   ["But me no buts.", "つべこべいうな(「しかし」「しかし」というな)"],
   ["After a calm comes a storm.", "嵐の前の静けさ(凪の後の嵐)"],
   ["A little leak will sink a great ship.", "蟻の穴から堤も崩れる(小さな漏れが大きな船をも沈める)"],
   ["Water sleeps, the enemy wakes.", "生き馬の目を抜く / 油断も隙も無い(水は眠れど、敵は眠らず)"],
   ["Patience wins the day.", "石の上にも三年(忍耐が勝利を収める)"],
   ["A fool and his money are easily parted.", "愚人はすぐ金を使い果たす"],
   ["A fox smells its own lair first.", "キツネは自分のねぐらをすぐに嗅ぎ当てる"],
   ["After dinner sit a while, after supper walk a mile.", "正餐の後は少し座れ、夕食の後は1マイル歩け"],
   ["After rain comes fair weather.", "雨降って地固まる(雨の後には晴天がくる)"],
   ["A guilty conscience needs no accuser.", "罪を自覚する者に告発者は不要"],
   ["A lie has no legs.", "真実は必ず明るみに出る(?には足がない（ので逃げられない）)"],
   ["A pessimist is simply an informed optimist.", "悲観主義者とは事情通の楽観主義者だ"],
   ["All good things come to an end.", "よいことはいつまでも続くわけではない(どんなよいことにも終わりがある)"],
   ["All is fair in love and war.", "恋と戦いではなんでも正しい"],
   ["A merry heart makes a long life.", "楽しければ長生き(楽しい心が長命をもたらす)"],
   ["A miss is as good as a mile.", "五十歩百歩(1インチの間違いも1マイルの間違いと同じ)"],
   ["An apple a day keeps the doctor away.", "１日一個のリンゴで医者いらず"],
   ["An empty bag will not stand upright.", "ない袖は振れぬ(からの袋はまっすぐ立たない)"],
   ["Another day, another dollar.", "お疲れ様(次の日も次のドル稼ぎ)"],
   ["A penny saved is a penny earned.", "1銭の節約は1銭のもうけ(1ペニーの節約は1ペニーの稼ぎと同じ)"],
   ["As you make your bed, so you must lie in it.", "自業自得(自分で用意したベッドには自分が寝なければならない)"],
   ["A woman's work is never done.", "女の仕事はきりがない"],
   ["Pride comes before a fall.", "驕る平家は久しからず(没落の前に傲慢がくる)"],
   ["Butter is gold in the morning, silver at noon, lead at night.", "朝のバターは金、昼は銀、夜は鉛"],
   ["Cross the stream where it is the shallowest.", "無理は禁物(川を渡るときは最も浅いところを選べ)"],
   ["Cut your losses.", "損切りは早めに"],
   ["Eat to live, don't live to eat.", "生きるために食え、食うために生きるな"],
   ["Everyone lies. And it's the truth.", "誰もが嘘をつく。それが本当だ。"],
   ["Every cloud has a silver lining.", "苦あれば楽あり(どんな雲にも銀の裏地がついている)"],
   ["Mind your own business.", "余計なおせっかい（をするな）(自分のことに気を遣え)"],
   ["Monkey see, monkey do.", "猿真似(猿は見たものをまねる)"],
   ["Orders are orders.", "命令は命令だ（従え）"],
   ["Rules are made to be broken.", "規則は破られるためにある"],
   ["Scorning is catching.", "人を呪わば穴二つ(軽蔑は感染しやすい)"],
   ["The door swings both ways.", "お互い様(ドアは内側にも外側にも開く)"],
   ["Variety is the spice of life.", "多様性は人生のスパイス"],
   ["Don't judge a book by its cover.", "見た目の判断は危険(本を表紙で判断してはならぬ)"],
   ["A house divided against itself cannot stand.", "別れたる家立つこと能わず"],
   ["If it ain't broke, don't fix it.", "触らぬ神に祟りなし(壊れてないものは直すな)"],
   ["If the cap fits, wear it.", "思い当たる節があれば素直に受け入れよ(帽子が自分に合うようなら、かぶれ)"],
   ["If you lie down with dogs, you will get up with fleas.", "朱に交われば赤くなる(犬と寝ると、蚤と起きることになる)"],
   ["If you pay peanuts, you get monkeys.", "低賃金で優秀な人材は雇えない(ピーナッツを支払えば猿がくる)"],
   ["If you want a thing done well, do it yourself.", "人を当てにするな(上手にやってもらいたければ、自分でやれ)"],
   ["Imitation is the sincerest form of flattery.", "真似することは最も誠実なお世辞"],
   ["In for a penny, in for a pound.", "やり始めたことは最後までやり通せ(1ペニーでやりかけたことは1ポンドまでやり通せ)"],
   ["It takes one to know one.", "自分のことは自分しかわからない(人を知りたければその人にならねばならぬ)"],
   ["Judge not, that ye be not judged.", "人を裁くな、裁かれざらんためなり"],
   ["Keep your chin up.", "上を向いて頑張れ(あごを上げて進め)"],
   ["Keep your powder dry.", "準備を怠るな(銃の火薬を乾いた状態に保て)"],
   ["Least said, soonest mended.", "口は禍の元(言葉少なければ改むるも容易)"],
   ["Let not the sun go down on your wrath.", "日が暮れるまで怒ったままでいてはいけません"],
   ["Let the buyer beware.", "買い手は（騙されないよう）注意せよ(「買い物の妥当性を判断するのは買い手の責任」の意)"],
   ["Let well alone.", "良しはそのままにせよ(満足なことはそのままにしておけ)"],
   ["Life is just a bowl of cherries.", "人生百花繚乱(人生はお椀に盛られたサクランボ（のように楽しいもの）)"],
   ["Pardon all but thyself.", "己を責めて、人を責むるな(自分以外のすべての人を許せ)"],
   ["Lightning never strikes twice in the same place.", "偶然は重ならない(雷は同じ場所に二度落ちない)"],
   ["Little pitchers have big ears.", "壁に耳あり（障子に目あり）(小さな水差しにも大きな耳（取っ手）がある)"],
   ["Little strokes fell great oaks.", "点滴岩をも穿つ(小さな打撃（の連続）が樫の大木を倒す)"],
   ["Live and let live.", "持ちつ持たれつ(自分も生き、他人も生かせ。)"],
   ["The love of money is the root of all evil.", "金銭欲は諸悪の根源"],
   ["Love makes the world go round.", "愛は世の中を動かす"],
   ["Thou shalt love thy neighbour as thyself.", "己のごとく汝の隣人を愛せよ(Love your neighbor as yourself.のこと)"],
   ["Manners maketh man.", "人間であるには礼節が必要(礼節が人を作る)"],
   ["Marriages are made in heaven.", "縁は異なもの味なもの(結婚は天国で（神により）決められる)"],
   ["Marriage is a lottery.", "縁は異なもの味なもの(結婚はくじ引きだ)"],
   ["Moderation in all things.", "何事もほどほどに(すべてのことに中庸を)"],
   ["Money doesn't grow on trees.", "金のなる木はない(金は気に生らない)"],
   ["Nature abhors a vacuum.", "自然は真空を嫌う（何かで埋めようとする）"],
   ["Never tell tales out of school.", "内輪話を外でするな(学校の話を外でするな)"],
   ["There's no such thing as bad publicity.", "悪評も宣伝のうち(悪い（宣伝にならない）宣伝などない)"],
   ["None so deaf as those who will not hear.", "心ここにあらざれば聞けども聞こえず(聞こうとしないものほどの聾者はいない)"],
   ["Nothing is certain but death and taxes.", "死と税金ほど確実に来るものはない"],
   ["Nothing succeeds like success.", "事成れば万事成る(成功ほど続いて起こるものはない)"],
   ["Oil and water don't mix.", "油と水は混ざらない"],
   ["Once a thief, always a thief.", "一度泥棒をするとやめられない"],
   ["Once bitten, twice shy.", "羮（あつもの）に懲りて膾（なます）を吹く(一度かまれると、二度目は怖気る)"],
   ["One hand washes the other.", "持ちつ持たれつ(片方の手がもう一方の手を洗う)"],
   ["Opposites attract.", "反対同士は互いに惹かれる"],
   ["Practice what you preach.", "有言実行(人に説くことは自分も実行せよ)"],
   ["A problem shared is a problem halved.", "悩みは打ち明けると半分になる"],
   ["Quality without quantity is little thought of.", "量なき質は軽んじられる"],
   ["A rising tide lifts all boats.", "トレンドに乗れば利益が出せる [投資](上げ潮はすべての船を持ち上げる)"],
   ["The road to hell is paved with good intentions.", "善意の人が地獄に行かないとは限らない(地獄への道は善意で敷き詰められている)"],
   ["Seek and you shall find.", "探せ、そうすれば見いだす"],
   ["Share and share alike", "分かち合え、平等に分かち合え"],
   ["Shrouds have no pockets.", "あの世にお金は持っていけない(死装束にポケットはない)"],
   ["A soft answer turneth away wrath.", "やさしい返事は怒りをそらす"],
   ["Tell the truth, and shame the Devil.", "真実を話してすっきりしなさい(真実を話して悪魔に恥をかかせよ)"],
   ["That which does not kill us makes us stronger.", "生きている限りの経験はすべて我々を強くしてくれる(我々を殺さないすべてのものが我々を強くする)"],
   ["The apple never falls far from the tree.", "蛙の子は蛙(リンゴが木から離れたところに落ちることはない)"],
   ["The best is the enemy of the good.", "中庸の徳(最善は善の敵)"],
   ["The best things in life are free.", "この世で最高のものはただ"],
   ["The bigger they are, the harder they fall.", "大物ほど転落は激しい(大きければ大きいほど倒れるのも激しい)"],
   ["The bottom line is the bottom line.", "（肝要な）問題は損益だ / 黒字か赤字かが問題だ(（最低線でも必要な）重要事項は（貸借対照表の）最終行だ)"],
   ["The cobbler always wears the worst shoes.", "紺屋の白袴(靴の修理屋はいつもぼろ靴を履いている)"],
   ["The customer is always right.", "お客様は神様(お客様は常に正しい)"],
   ["The devil is in the details.", "詰めが大事(悪魔は細部にいる)"],
   ["The devil looks after his own.", "憎まれっ子世に憚（はばか）る(悪魔は自分の面倒をよく見る)"],
   ["The fat is in the fire.", "もう取り返しがつかない(脂はもう火にそそがれた)"],
   ["The hand that rocks the cradle rules the world.", "世界の支配者を作るのは母親(ゆりかごを揺らす手が世界を支配する)"],
   ["Whoever refuses to work is not allowed to eat.", "働かざるもの食うべからず"],
   ["The wages of sin is death.", "罪の報いは死なり"],
   ["The whole is greater than the sum of the parts.", "シナジー効果 / 相乗効果(全体は個々の合計より大きい)"],
   ["There’s a time and a place for everything.", "時と場所をわきまえよ / 常識をわきまえよ(何事にも適切な時と場所がある)"],
   ["There's many a slip twixt cup and lip.", "好事（こうじ）魔多し / 油断大敵(茶碗と唇の間でも失敗は起こるもの)"],
   ["There's a sucker born every minute.", "カモになる青二才は山ほどいる(騙されやすい青二才は1分ごとに生まれる)"],
   ["Thou shalt not kill.", "汝殺すなかれ([聖書の言葉で現代英語では You shall not kill.])"],
   ["Time is a great healer.", "苦しみも時がたてば忘れる(時は偉大な癒しだ)"],
   ["Time will tell.", "時がたてばわかる"],
   ["To the victor go the spoils.", "勝利者は戦利品も手に入れる"],
   ["Two is company, but three's a crowd.", "二人は連れ合い、三人は人ごみ"],
   ["Two wrongs don't make a right.", "悪事に悪事を返してもよくはならない(悪事を悪事で上塗りしても正しくはならない)"],
   ["Virtue is its own reward.", "美徳はそれ自らが報いである"],
   ["Walnuts and pears you plant for your heirs.", "子孫への積善(胡桃と梨は子孫のために植える)"],
   ["Waste not, want not.", "むだせずば事欠かず(無駄をしなければ欠乏もない)"],
   ["A way to a man's heart is through his stomach.", "男の心は食事でつかむ(男の心に通じる道は彼のおなか)"],
   ["What goes up must come down.", "驕る平家は久しからず(登ったものは落ちねばならぬ)"],
   ["What one loses on the swings one makes up on the roundabouts.", "一方で損しても他方で取り返す(ブランコでの損は回転木馬で取り返す)"],
   ["What's sauce for the goose is sauce for the gander.", "一方に当てはまることは他方にも当てはまる(雌ガチョウにとってのソースは雄ガチョウにとってもソースだ)"],
   ["When the going gets tough, the tough get going.", "進行がタフに（厳しく）なるとタフな人が動き出す"],
   ["What the eye doesn't see the heart doesn't grieve over.", "見ぬは極楽、知らぬは仏(目に見えないことを悲しむことはない)"],
   ["When cats are mousing, they won't mew.", "鼠捕る猫爪を隠す"],
   ["The dog that trots about finds a bone.", "犬も歩けば棒に当たる(歩き回る犬は骨を見つける)"],
   ["It's like water on a duck's back.", "蛙の面に水 / 馬耳東風(アヒルの背中に水をかけるようなもの)"],
   ["Great profits, great risks.", "ハイリスク、ハイリターン / 虎穴に入らずんば虎子を得ず(大きい利益を上げるには大きいリスクがある)"],
   ["Wake not a sleeping lion.", "寝た子を起こすな(寝たライオンを起こすな)"],
   ["Where there's muck there's brass.", "富と不潔は隣りあわせ(汚物のある所に金がある)"],
   ["Muck and money go together.", "富と不潔は隣りあわせ"],
   ["Go to the ant, thou sluggard.", "汝怠け者よ、蟻に見習え(汝怠け者よ、蟻の元へ行け)"],
   ["The dog that fetches will carry.", "人の悪口を言う人はあなたの悪口も言っている(持ってくる犬はまた持っていく)"],
   ["Dogs bark as they are bred.", "内の習いは外で出る(犬は育てられたように吠える)"],
   ["Try a horse by riding him, and judge a man by living with him.", "馬には乗ってみよ、人には添うてみよ"],
   ["Ready money will away.", "手元の金はすぐ使ってしまう(すぐ使える現金はすぐ行ってしまう)"],
   ["Venture a small fish and catch a great one.", "海老で鯛を釣る(小魚を犠牲にして大魚を獲る)"],
   ["The tongue wounds more than a lance.", "口は災いの門(口は槍よりも人を傷つける)"],
   ["The tongue can no man tame.", "舌を制し得る人は一人もいない"],
   ["Call a spade a spade.", "歯に衣を着せぬ(スコップをスコップと呼ぶ)"],
   ["The cat shuts its eyes while it steals cream.", "耳を掩うて鈴を盗む(猫は目を閉じてクリームを盗む)"],
   ["fighting with one's back to the wall", "背水の陣(壁を背にして戦う)"],
   ["Variety is the mother of enjoyment.", "多様性は快楽の母"],
   ["Failure is the stepping stone to success.", "失敗は成功の母(失敗は成功への踏み石)"],
   ["One master in a house is enough,", "船頭多くして船山に上る(一家に家長は一人で十分)"],
   ["The belly is not filled with fair words.", "花より団子(美辞麗句で腹は膨れない)"],
   ["To the hungry no bread is bad.", "空腹にまずいものなし(腹が減ればどんなパンもおいしい)"],
   ["To burn the midnight oil.", "蛍雪の功を積む(夜中まで灯をつけて学ぶ)"],
   ["The tail wags the dog.", "下克上 / 本末転倒(しっぽが犬を振る)"],
   ["the law of the jungle", "弱肉強食(ジャングルの掟（おきて）)"],
   ["Do the best and leave the rest to God.", "人事を尽くして天命を待つ(最善を尽くして、あとは神に任せよ)"],
   ["Too much is as bad as too little.", "過ぎたるは猶及ばざるが如し"],
   ["Who goes slowly goes far.", "大器晩成(ゆっくり進む者が遠くまで行く)"],
   ["What is bought is cheaper than a gift.", "タダより高い物はない(買ったものはもらったものより安い)"],
   ["Wealth of words is not eloquence.", "多弁は雄弁にあらず"],
   ["To carry a lantern in midday.", "月夜に提灯 / 無用の長物(昼間に灯りをもっていく)"],
   ["A bad penny always turns up.", "望まぬ客は現れる(悪貨は必ず戻ってくる)"],
   ["A change is as good as a rest.", "気晴らしは休養に値する"],
   ["A good man is hard to find.", "善人は見つけがたい[少ない]"],
   ["A hungry man is an angry man.", "空腹になると怒りっぽくなる"],
   ["There is kindness to be found everywhere.", "渡る世間に鬼はなし(親切は至る所にある)"],
   ["A prophet is not recognized in his own land.", "預言者[賢者]は己の里では認められ難い"],
   ["A thing of beauty is a joy forever.", "美しいものは永遠の喜び"],
   ["Absence makes the heart grow fonder.", "離れていると恋しさ百倍(離れていることが恋しさを募らせる)"],
   ["An Englishman's home is his castle.", "イギリス人の家は彼の要塞（であり、何びとも侵すことはできない）"],
   ["As soon as man is born, he begins to die.", "誕生は死の始まり(人は生まれると同時に死に向かう)"],
   ["Ask no questions and hear no lies.", "質問しなければ、嘘を聞くこともない"],
   ["Beauty is but skin-deep.", "美人というも皮一重"],
   ["Behind every great man there's a great woman.", "内助の功(偉大な男性の後ろには偉大な女性がいる)"],
   ["Better die with honor than live with shame.", "生き恥かくより死ぬがまし"],
   ["Better the devil you know than the devil you don't know.", "知らぬ神より馴染みの鬼(知らない悪魔より知っている悪魔のほうがまし)"],
   ["Business before pleasure.", "遊ぶことよりまず仕事(快楽の前に仕事)"],
   ["Children are poor men’s riches.", "子は宝(子は貧乏人の富)"],
   ["Clogs to clogs in three generations.", "築いた財産も三代目まで(木靴から木靴へ三代)"],
   ["Comparisons are odious.", "比較はいやなもの"],
   ["Count your blessings.", "（愚痴より）恵みを数えよう"],
   ["Crime does not pay.", "犯罪は割に合わない"],
   ["Curiosity killed the cat.", "他人の詮索を慎め(好奇心が猫を殺した)"],
   ["Death always comes too early or too late.", "死は丁度良い時には訪れない"],
   ["Death pays all debts.", "死はすべてを清算する"],
   ["Diligence is the mother of good fortune.", "勤勉は幸運を呼ぶ(勤勉は幸運の母)"],
   ["Discretion is the better part of valor.", "君子危うきに近寄らず(思慮分別が勇気の大部分)"],
   ["Divide and rule.", "分割統治(分割して統治せよ)"],
   ["Do to others what you would be done by.", "己の欲するところを人に施せ [聖書](あなたがしてもらいたいように人にもしてあげなさい)"],
   ["Do as you would be done by.", "あなたがしてもらいたいように人にもしてあげなさい"],
   ["Do not wear out your welcome.", "長居すると嫌われる(歓迎を使い果たすな)"],
   ["Don’t burn your bridges behind you.", "逃げ道を断つな(背後の橋を燃やすな)"],
   ["Don’t change horses in midstream.", "初志貫徹せよ(川の真ん中で馬を乗り換えるな)"],
   ["Don’t go near the water until you learn how to swim.", "泳ぎを覚えるまで水に近づくな"],
   ["Don’t keep a dog and bark yourself.", "雇人の仕事を自分でするな(犬を飼ったら、自分で吠えるな)"],
   ["Every man has his price.", "地獄の沙汰も金次第(人にはそれぞれ値段がある。)"],
   ["Familiarity breeds contempt.", "親しき中にも礼儀あり(気安さは軽蔑を生む)"],
   ["Health is not valued till sickness comes.", "病気になって初めて健康のありがたさがわかる(病気になるまで健康が評価されない)"],
   ["from the cradle to the grave", "ゆりかごから墓場まで（の社会保障）"],
   ["Lay up treasures in heaven.", "天に宝を積め"]
]


if __name__ == '__main__':
    w = get_wisdom()
    print(w)
